name: CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build: 
    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Login to Harbor
      run: echo ${{ secrets.HARBOR_PASSWORD }} | docker login -u ${{ secrets.HARBOR_USERNAME }} --password-stdin 192.168.56.200

    - name: Build image
      run: |
        docker build -t 192.168.56.200/mylittlerecipebook/mlr-dev-fe-img:${{ github.run_number }} -f Dockerfile .
    
    - name: Push Docker image
      run: |
        docker push 192.168.56.200/mylittlerecipebook/mlr-dev-fe-img:${{ github.run_number }}
         
    - name: Clone GitOps Repo
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
      run: |
        git clone https://x-access-token:${{ secrets.TOKEN_GITHUB }}@github.com/aws-final-6/GitOps_Repo.git
        cd GitOps_Repo
        
    - name: Install yq without sudo
      run: |
        wget -qO ~/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
        chmod +x ~/yq
    
    - name: Update deployment.yaml with new image
      run: |
        ~/yq -i '.spec.template.spec.containers[0].image = "192.168.56.200/mylittlerecipebook/mlr-dev-fe-img:${{ github.run_number }}"' deployment.yaml
      
    - name: Configure git email
      run: |
        git config --global user.email "${{ secrets.EMAIL_GITHUB }}"
        
    - name: Configure git username
      run: |
        git config --global user.name "${{ secrets.USERNAME_GITHUB }}"
         
    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
      run: |
        cd GitOps_Repo
        git add deployment.yaml
        git commit -m "Update image to 192.168.56.200/mylittlerecipebook/mlr-dev-fe-img:${{ github.run_number }}"
        git push https://x-access-token:${{ secrets.TOKEN_GITHUB }}@github.com/aws-final-6/GitOps_Repo.git
